package DB;
// Generated Nov 9, 2016 6:54:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name="car"
    ,catalog="cit360_team_e_skills_db"
)
public class Car  implements java.io.Serializable {


     private Integer id;
     private Owner owner;
     private String year;
     private String make;
     private String model;
     private String color;

    public Car() {
    }

    public Car(Owner owner, String year, String make, String model, String color) {
       this.owner = owner;
       this.year = year;
       this.make = make;
       this.model = model;
       this.color = color;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="owner_id", nullable=false)
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    
    @Column(name="year", nullable=false, length=4)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="make", nullable=false, length=45)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="model", nullable=false, length=45)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="color", nullable=false, length=45)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


