package DB;
// Generated Nov 9, 2016 6:54:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JasonJson generated by hbm2java
 */
@Entity
@Table(name="jason_json"
    ,catalog="cit360_team_e_skills_db"
)
public class JasonJson  implements java.io.Serializable {


     private int id;
     private String laxJson;
     private String strictJson;
     private String uniqueJson;

    public JasonJson() {
    }

	
    public JasonJson(int id) {
        this.id = id;
    }
    public JasonJson(int id, String laxJson, String strictJson, String uniqueJson) {
       this.id = id;
       this.laxJson = laxJson;
       this.strictJson = strictJson;
       this.uniqueJson = uniqueJson;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="lax_json", length=1024)
    public String getLaxJson() {
        return this.laxJson;
    }
    
    public void setLaxJson(String laxJson) {
        this.laxJson = laxJson;
    }

    
    @Column(name="strict_json", length=1024)
    public String getStrictJson() {
        return this.strictJson;
    }
    
    public void setStrictJson(String strictJson) {
        this.strictJson = strictJson;
    }

    
    @Column(name="unique_json", length=1024)
    public String getUniqueJson() {
        return this.uniqueJson;
    }
    
    public void setUniqueJson(String uniqueJson) {
        this.uniqueJson = uniqueJson;
    }




}


