package DB;
// Generated Nov 9, 2016 6:54:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SkillsTable generated by hbm2java
 */
@Entity
@Table(name="skills_table"
    ,catalog="cit360_team_e_skills_db"
)
public class SkillsTable  implements java.io.Serializable {


     private Integer skillsId;
     private String skillCategory;
     private String skillName;
     private Set<MemberTable> memberTables = new HashSet<MemberTable>(0);

    public SkillsTable() {
    }

	
    public SkillsTable(String skillCategory, String skillName) {
        this.skillCategory = skillCategory;
        this.skillName = skillName;
    }
    public SkillsTable(String skillCategory, String skillName, Set<MemberTable> memberTables) {
       this.skillCategory = skillCategory;
       this.skillName = skillName;
       this.memberTables = memberTables;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="skillsID", unique=true, nullable=false)
    public Integer getSkillsId() {
        return this.skillsId;
    }
    
    public void setSkillsId(Integer skillsId) {
        this.skillsId = skillsId;
    }

    
    @Column(name="skill_category", nullable=false, length=40)
    public String getSkillCategory() {
        return this.skillCategory;
    }
    
    public void setSkillCategory(String skillCategory) {
        this.skillCategory = skillCategory;
    }

    
    @Column(name="skillName", nullable=false, length=40)
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="skillsTable")
    public Set<MemberTable> getMemberTables() {
        return this.memberTables;
    }
    
    public void setMemberTables(Set<MemberTable> memberTables) {
        this.memberTables = memberTables;
    }




}


