package DB;
// Generated Nov 9, 2016 6:54:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserTable generated by hbm2java
 */
@Entity
@Table(name="user_table"
    ,catalog="cit360_team_e_skills_db"
)
public class UserTable  implements java.io.Serializable {


     private String username;
     private MemberTable memberTable;
     private String password;
     private boolean adminuser;

    public UserTable() {
    }

    public UserTable(String username, MemberTable memberTable, String password, boolean adminuser) {
       this.username = username;
       this.memberTable = memberTable;
       this.password = password;
       this.adminuser = adminuser;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=40)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="memberID", nullable=false)
    public MemberTable getMemberTable() {
        return this.memberTable;
    }
    
    public void setMemberTable(MemberTable memberTable) {
        this.memberTable = memberTable;
    }

    
    @Column(name="password", nullable=false, length=40)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="adminuser", nullable=false)
    public boolean isAdminuser() {
        return this.adminuser;
    }
    
    public void setAdminuser(boolean adminuser) {
        this.adminuser = adminuser;
    }




}


