package DB;
// Generated Oct 25, 2016 6:36:24 PM by Hibernate Tools 4.3.1



/**
 * LocationTable generated by hbm2java
 */
public class LocationTable  implements java.io.Serializable {


     private Integer wardId;
     private String wardName;
     private String stakeName;

    public LocationTable() {
    }

    public LocationTable(String wardName, String stakeName) {
       this.wardName = wardName;
       this.stakeName = stakeName;
    }
   
    public Integer getWardId() {
        return this.wardId;
    }
    
    public void setWardId(Integer wardId) {
        this.wardId = wardId;
    }
    public String getWardName() {
        return this.wardName;
    }
    
    public void setWardName(String wardName) {
        this.wardName = wardName;
    }
    public String getStakeName() {
        return this.stakeName;
    }
    
    public void setStakeName(String stakeName) {
        this.stakeName = stakeName;
    }




}


