package DB;
// Generated Oct 25, 2016 6:36:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MemberTable generated by hbm2java
 */
public class MemberTable  implements java.io.Serializable {


     private int memberId;
     private AddressTable addressTable;
     private SkillsTable skillsTable;
     private String lname;
     private String fname;
     private String mname;
     private int phone;
     private int phoneType;
     private String email;
     private Integer wardId;
     private Set userTables = new HashSet(0);

    public MemberTable() {
    }

	
    public MemberTable(int memberId, AddressTable addressTable, SkillsTable skillsTable, String lname, String fname, int phone, int phoneType, String email) {
        this.memberId = memberId;
        this.addressTable = addressTable;
        this.skillsTable = skillsTable;
        this.lname = lname;
        this.fname = fname;
        this.phone = phone;
        this.phoneType = phoneType;
        this.email = email;
    }
    public MemberTable(int memberId, AddressTable addressTable, SkillsTable skillsTable, String lname, String fname, String mname, int phone, int phoneType, String email, Integer wardId, Set userTables) {
       this.memberId = memberId;
       this.addressTable = addressTable;
       this.skillsTable = skillsTable;
       this.lname = lname;
       this.fname = fname;
       this.mname = mname;
       this.phone = phone;
       this.phoneType = phoneType;
       this.email = email;
       this.wardId = wardId;
       this.userTables = userTables;
    }
   
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }
    public AddressTable getAddressTable() {
        return this.addressTable;
    }
    
    public void setAddressTable(AddressTable addressTable) {
        this.addressTable = addressTable;
    }
    public SkillsTable getSkillsTable() {
        return this.skillsTable;
    }
    
    public void setSkillsTable(SkillsTable skillsTable) {
        this.skillsTable = skillsTable;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public int getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(int phoneType) {
        this.phoneType = phoneType;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getWardId() {
        return this.wardId;
    }
    
    public void setWardId(Integer wardId) {
        this.wardId = wardId;
    }
    public Set getUserTables() {
        return this.userTables;
    }
    
    public void setUserTables(Set userTables) {
        this.userTables = userTables;
    }




}


