package DB;
// Generated Oct 25, 2016 6:36:24 PM by Hibernate Tools 4.3.1



/**
 * UserTable generated by hbm2java
 */
public class UserTable  implements java.io.Serializable {


     private String username;
     private MemberTable memberTable;
     private String password;
     private boolean adminuser;

    public UserTable() {
    }

    public UserTable(String username, MemberTable memberTable, String password, boolean adminuser) {
       this.username = username;
       this.memberTable = memberTable;
       this.password = password;
       this.adminuser = adminuser;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public MemberTable getMemberTable() {
        return this.memberTable;
    }
    
    public void setMemberTable(MemberTable memberTable) {
        this.memberTable = memberTable;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAdminuser() {
        return this.adminuser;
    }
    
    public void setAdminuser(boolean adminuser) {
        this.adminuser = adminuser;
    }




}


